name: heticare_screen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  persistent_bottom_nav_bar: ^6.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/history_selected.svg
    - assets/history_unselected.svg

    - assets/home_selected.svg
    - assets/home_unselected.svg

    - assets/notification.svg
    - assets/waitingApproval.svg

    - assets/setting_selected.svg
    - assets/setting_unselected.svg
